pipeline {
    agent {
        node {
            label 'docker-agent-apline'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building project'
                sh '''
                cd task3
                java -v
                mvn clean install
                '''
            }
        }
        stage('Validate') {
            steps {
                echo 'Validating project'
                sh '''
                cd task3
                mvn test
                mvn checkstyle:check
                '''
            }
        }
    }
}