pipeline {
    agent {
        node {
            label 'docker-agent-apline'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building project'
                echo 'Build'
            }
        }
        stage('Validate') {
            steps {
                echo 'Validating project'
            }
        }
    }
}