services:
  hello-world-html: &hello-world-html
    env_file:
      - hello-world.env
    image: hashicorp/http-echo:1.0.0
    command: ["-listen=:80", "-text=${GREETING}"]
    ports:
      - 8080:80
  hello-world-html-1:
    <<: *hello-world-html
    ports:
      - 8081:80
  hello-world-html-2:
    <<: *hello-world-html
    ports:
      - 8082:80
  hello-world-html-3:
    <<: *hello-world-html
    ports:
      - 8083:80
  hello-world-html-4:
    <<: *hello-world-html
    ports:
      - 8084:80
  database:
    env_file:
      - database.env
    container_name: database
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p ${PGPORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 54321:54321
  spring-boot-app:
    env_file:
      - spring-boot.env
      - database.env
    depends_on:
      database:
        condition: service_healthy
    image: vroniu/javadevops:1.1.3
    ports:
      - 8010:8888
    environment:
      - DEVOPS=${DEVOPS}
      - DATABASE_NAME=database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}