name: Check application.yml

on: pull_request

env:
    FILENAME: task3/src/main/resources/application.yml

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.10'
            - name: Install YAML Linter
              run: pip install yamllint
            - name: Run YAML Linter
              run: yamllint ${{env.FILENAME}}


